import json, re

# Flattened source list, one entry per distinct sweepable source.
# Section XV (Superseded Reference) intentionally excluded — not new source content.
sources = [
  # I. Anime & Manga
  ("JoJo's Bizarre Adventure","Anime & Manga"),
  ("Dragon Ball Z","Anime & Manga"),
  ("Date A Live","Anime & Manga"),
  ("Fist of the North Star","Anime & Manga"),
  ("One Piece","Anime & Manga"),
  ("Naruto","Anime & Manga"),
  ("Pokemon","Anime & Manga"),
  ("Digimon","Anime & Manga"),
  ("City Hunter","Anime & Manga"),
  ("Cowboy Bebop","Anime & Manga"),
  ("Sailor Moon","Anime & Manga"),
  ("Heaven's Lost Property","Anime & Manga"),
  ("Kenichi the Mightiest Disciple","Anime & Manga"),
  ("Kinnikuman","Anime & Manga"),
  ("Getter Robo","Anime & Manga"),
  ("Gundam (all centuries, incl. G Gundam)","Anime & Manga"),
  ("Mazinger","Anime & Manga"),
  # II. Comics, Western Animation & Toys
  ("Marvel","Comics/Animation/Toys"),
  ("DC","Comics/Animation/Toys"),
  ("Transformers","Comics/Animation/Toys"),
  ("He-Man / Masters of the Universe","Comics/Animation/Toys"),
  ("Thomas the Tank Engine","Comics/Animation/Toys"),
  # III. Film & TV
  ("Star Wars","Film & TV"),
  ("Star Trek","Film & TV"),
  ("Mad Max","Film & TV"),
  ("all Pixar films","Film & TV"),
  ("major live-action Disney films","Film & TV"),
  ("Kingdom Hearts (binding cosmology of the Disney set)","Film & TV"),
  # IV. Music
  ("2112 (Rush)","Music"),
  ("Clockwork Angels (Rush)","Music"),
  # V. Fighting Games
  ("Tekken","Fighting Games"),
  ("Street Fighter","Fighting Games"),
  ("Killer Instinct","Fighting Games"),
  ("Soul Calibur","Fighting Games"),
  # VI. Shooters & Military
  ("Call of Duty Zombies","Shooters & Military"),
  ("all Black Ops","Shooters & Military"),
  ("all Modern Warfare","Shooters & Military"),
  ("all Battlefield","Shooters & Military"),
  ("Halo","Shooters & Military"),
  ("Destiny 1 & 2","Shooters & Military"),
  ("Gears of War","Shooters & Military"),
  ("Doom","Shooters & Military"),
  ("Half-Life","Shooters & Military"),
  ("Team Fortress 2","Shooters & Military"),
  ("Left 4 Dead","Shooters & Military"),
  ("all Metro","Shooters & Military"),
  ("XCOM","Shooters & Military"),
  ("Splinter Cell","Shooters & Military"),
  ("Rainbow Six","Shooters & Military"),
  ("Ghost Recon","Shooters & Military"),
  ("The Division","Shooters & Military"),
  ("HAWX","Shooters & Military"),
  ("EndWar","Shooters & Military"),
  ("Overwatch","Shooters & Military"),
  # VII. RPGs & Action Games
  ("all Final Fantasy","RPGs & Action Games"),
  ("all Elder Scrolls","RPGs & Action Games"),
  ("all Fallout","RPGs & Action Games"),
  ("Diablo","RPGs & Action Games"),
  ("Path of Exile","RPGs & Action Games"),
  ("Mass Effect","RPGs & Action Games"),
  ("Metal Gear Solid","RPGs & Action Games"),
  ("Yakuza","RPGs & Action Games"),
  ("Vampyr","RPGs & Action Games"),
  ("Vampire: The Masquerade","RPGs & Action Games"),
  ("Disco Elysium","RPGs & Action Games"),
  ("The Binding of Isaac","RPGs & Action Games"),
  ("Darksiders","RPGs & Action Games"),
  ("Katana Zero","RPGs & Action Games"),
  ("Hotline Miami","RPGs & Action Games"),
  ("Henry Stickmin","RPGs & Action Games"),
  ("Risk of Rain","RPGs & Action Games"),
  ("the Skate games","RPGs & Action Games"),
  # VIII. Strategy, Sim & Sandbox
  ("Stellaris","Strategy/Sim/Sandbox"),
  ("Factorio","Strategy/Sim/Sandbox"),
  ("RimWorld","Strategy/Sim/Sandbox"),
  ("all Creeper World","Strategy/Sim/Sandbox"),
  ("all Bloons TD","Strategy/Sim/Sandbox"),
  ("Terraria","Strategy/Sim/Sandbox"),
  ("Minecraft","Strategy/Sim/Sandbox"),
  ("Song of Syx","Strategy/Sim/Sandbox"),
  ("Super Energy Apocalypse 1 & 2","Strategy/Sim/Sandbox"),
  ("Wizard with a Gun","Strategy/Sim/Sandbox"),
  ("Cosmoteer","Strategy/Sim/Sandbox"),
  ("Star Realms","Strategy/Sim/Sandbox"),
  ("Palworld","Strategy/Sim/Sandbox"),
  ("ANEURISM IV","Strategy/Sim/Sandbox"),
  ("Fortnite","Strategy/Sim/Sandbox"),
  ("Rocket League","Strategy/Sim/Sandbox"),
  ("War Thunder + World of Tanks/Warplanes/Warships (space-refit)","Strategy/Sim/Sandbox"),
  # IX. Card Game
  ("Magic: The Gathering — all planes","Card Game"),
  # X. Literature & Tabletop War
  ("The Lord of the Rings","Literature & Tabletop War"),
  ("Dune","Literature & Tabletop War"),
  ("the Lovecraftian mythos","Literature & Tabletop War"),
  ("Warhammer 40,000","Literature & Tabletop War"),
  ("Warhammer Fantasy","Literature & Tabletop War"),
  # XI. Real-World Traditions
  ("Pantheon: Greek","Real-World Traditions"),
  ("Pantheon: Roman","Real-World Traditions"),
  ("Pantheon: Norse","Real-World Traditions"),
  ("Pantheon: Egyptian","Real-World Traditions"),
  ("Pantheon: Mesoamerican","Real-World Traditions"),
  ("Pantheon: Native American","Real-World Traditions"),
  ("Pantheon: Hindu","Real-World Traditions"),
  ("Pantheon: Abrahamic","Real-World Traditions"),
  ("Pantheon: Japanese","Real-World Traditions"),
  ("Pantheon: Korean","Real-World Traditions"),
  ("Pantheon: Chinese","Real-World Traditions"),
  ("Pantheon: Polynesian","Real-World Traditions"),
  ("Pantheon: Inuit","Real-World Traditions"),
  ("major fantasy pantheons","Real-World Traditions"),
  ("the Solomonic tradition (Goetia, the Keys, the Shem angels)","Real-World Traditions"),
  ("Western astrology","Real-World Traditions"),
  ("Eastern astrology (BaZi, jyotisha)","Real-World Traditions"),
  ("witchcraft traditions in full","Real-World Traditions"),
  # XII. Original IP
  ("The Amethyst / Cockroach King screenplay (Chroma Wastes)","Original IP"),
  # XIII. The Folder — Official D&D
  ("Player's Handbook","Folder: Official D&D"),
  ("Dungeon Master's Guide","Folder: Official D&D"),
  ("Monster Manual","Folder: Official D&D"),
  ("Xanathar's Guide to Everything","Folder: Official D&D"),
  ("Mordenkainen's Tome of Foes","Folder: Official D&D"),
  ("Volo's Guide to Monsters","Folder: Official D&D"),
  ("Sword Coast Adventurer's Guide","Folder: Official D&D"),
  ("Eberron: Rising from the Last War","Folder: Official D&D"),
  ("Explorer's Guide to Wildemount","Folder: Official D&D"),
  ("Guildmasters' Guide to Ravnica","Folder: Official D&D"),
  ("Mythic Odysseys of Theros","Folder: Official D&D"),
  ("Curse of Strahd","Folder: Official D&D"),
  ("Descent into Avernus","Folder: Official D&D"),
  ("Ghosts of Saltmarsh","Folder: Official D&D"),
  ("Rime of the Frostmaiden","Folder: Official D&D"),
  ("Lost Mines of Phandelver","Folder: Official D&D"),
  ("Waterdeep: Dragon Heist","Folder: Official D&D"),
  ("Dungeon of the Mad Mage","Folder: Official D&D"),
  ("Tomb of Annihilation","Folder: Official D&D"),
  ("Storm King's Thunder","Folder: Official D&D"),
  ("Out of the Abyss","Folder: Official D&D"),
  ("Princes of the Apocalypse","Folder: Official D&D"),
  ("Hoard of the Dragon Queen","Folder: Official D&D"),
  ("Rise of Tiamat","Folder: Official D&D"),
  ("Tales from the Yawning Portal","Folder: Official D&D"),
  ("Acquisitions Incorporated","Folder: Official D&D"),
  ("Adventurers League","Folder: Official D&D"),
  ("Extra Life","Folder: Official D&D"),
  ("Unearthed Arcana (incl. the Planeshift documents)","Folder: Official D&D"),
  # XIV. The Folder — Third Party & Creators
  ("KibblesTasty (techno-psionic line)","Folder: Third Party"),
  ("Mage Hand Press","Folder: Third Party"),
  ("Kobold Press (Midgard Heroes Handbook, Midgard Worldbook)","Folder: Third Party"),
  ("Arcanum Worlds (Odyssey of the Dragonlords)","Folder: Third Party"),
  ("Critical Role (Tal'Dorei Campaign Setting)","Folder: Third Party"),
  ("Genuine Fantasy Press (Forgotten Secrets)","Folder: Third Party"),
  ("DMs Guild: Heroes of Hell","Folder: Third Party"),
  ("DMs Guild: Mirt's Undermountain Survival Guide","Folder: Third Party"),
  ("DMs Guild: The Great Dale","Folder: Third Party"),
  ("DMs Guild: Walrock Homebrew","Folder: Third Party"),
  ("DMs Guild: Wayfinder's Guide to Eberron","Folder: Third Party"),
  ("DMs Guild: Xanathar's Lost Notes to Everything Else","Folder: Third Party"),
  ("swordmeow's Atavist","Folder: Third Party"),
  ("Yorviing's Arcane Grimoire","Folder: Third Party"),
  ("A Plethora of Paladins","Folder: Third Party"),
  ("The Elements Beyond","Folder: Third Party"),
  ("Dr. Firestorm's Engineering Corps","Folder: Third Party"),
  ("swecky's Nature Traditions","Folder: Third Party"),
  ("JMBrew","Folder: Third Party"),
  ("the FFXIV / Eorzea conversion","Folder: Third Party"),
  ("aurora_mods (Way of the Inkmaster)","Folder: Third Party"),
  ("Curious DM Investigations (the Sharkin)","Folder: Third Party"),
  ("KBP Unlikely Heroes","Folder: Third Party"),
  ("Savant","Folder: Third Party"),
  ("the Witch Tradition","Folder: Third Party"),
  ("Draconic Cult Relics","Folder: Third Party"),
  ("Native Combat Traditions","Folder: Third Party"),
  ("Prime World Equipment","Folder: Third Party"),
  ("the Root Companions","Folder: Third Party"),
  ("the Weaveshaper Ateliers","Folder: Third Party"),
  ("the Sex Worker background","Folder: Third Party"),
]

def sortkey(name):
    n = name.lower()
    n = re.sub(r'^(the|all|a|major)\s+', '', n)
    n = re.sub(r'[^a-z0-9 ]', '', n)
    return n.strip()

recs = []
for i,(name,cat) in enumerate(sources):
    recs.append({"name": name, "category": cat, "status": "pending"})

recs.sort(key=lambda r: sortkey(r["name"]))
for i,r in enumerate(recs):
    r["seq"] = i+1

print(len(recs))
json.dump(recs, open('/home/claude/panscriptum/sweep/SWEEP_ROLL.json','w'), indent=2)
for r in recs:
    print(r["seq"], r["name"], "  [",r["category"],"]")
