const CONC=[
["The Concordat of Courts","Treaty","drafted c. −9,200 AS","The divine civil service's founding instrument: domains partitioned into Offices, mortals shielded, the Theomachies never resumed.","VIII.5.1"],
["The Masquerade General","Treaty","902 AS","The veil rebuilt as law after the Night of Broken Veils; signatories from Kindred courts, hero institutions, three Offices, the Communion.","VIII.5.3"],
["The Compact of Mirrors","Treaty","604 AS","Dual sovereignty for refractions — the twin-Ravnica settlement, controlling precedent for every mirror case since.","VIII.5.4"],
["The Zeno Accords","Treaty","1,113 AS","Erasure-stakes contest reconstituted as the Circuit's supreme court, under a child-king destroyer's carefully worded smile.","VIII.5.5"],
["The Gravel Armistice","Treaty","1,048 AS","Signed; violated within the hour; never lapsed. Annotation in full: 'Still going.'","VIII.5.6"],
["The Pale Accords","Treaty","1,201 AS","The only treaty offered to the Silence. The terms survive. The signatures do not.","VIII.5.7"],
["The Arrakis Concession","Trade agreement","771 AS","Settlement of the Spice Crisis: who may see the deep waters before sailing them. The most-litigated fine print in existence.","VIII.5.9"],
["The Roadwright Charters","Charter","400s AS","The licenses that made crossing a profession; the guilds' constitution.","VIII.4.2"],
["The Pilot's Oath","Law","421 AS","'The sea before the cargo, the passenger before the sea, the chart before everything.' Written by a disaster; kept by everyone.","VIII.4.9"],
["The Long Embargo","Policy","1,001 AS","The Imperium seals its universe against the Roads. Largest voluntary quarantine in history; still in force; priced at the back door.","VIII.4.14"],
["The Survey Charter","Charter","c. 300 AS","Non-interference as constitutional law: the Veiled Survey's mandate over 4,912 watched worlds.","I.9"],
["The Freeport Neutrality Compact","Treaty","388 AS","The harbor belongs to no flag; the memorial was built first, the bar second, and those remain the priorities.","VIII.5.15"],
["The Senzu Escort Compact","Trade agreement","standing","A bean that undoes attrition travels like a head of state; this is the paperwork that moves it.","VIII.7.11"],
["The Energon Collateral Accords","Trade agreement","post-934 AS","After the Panic: energon may collateralize nothing larger than the hull that carries it.","VIII.7.4"],
["The Gil–Credit Convertibility Memorandum","Trade agreement","standing","The retail spine of the Concordance economy; renegotiated quarterly, resented perpetually.","VIII.13.9"],
["The Bonded Vault Charter","Charter","standing","The Freeport's neutral custody law: what goes in a drawer stays in a drawer, whoever conquers whom.","VI.2"],
["The Relic Auction Convention","Trade agreement","standing","Embassy Row's rules for selling things that should possibly not be sold; the Office of War holds three standing vetoes.","VI.2"],
["The Story-Trade Licensing Act","Law","post-Rabiah ruling","Narrative has market and causal value; bards are licensed like pilots; exports screened for A1 contamination.","II.E.3"],
["The Sundering","Event","0 AS","The wound: the walls raised, Terra's futures shattered, the Silence entered through the accession itself. E-0000-SUND ⟦↑17⟧.","VIII.3"],
["The First Crossing","Event","212 AS","Deliberate transit of the walls, at last. Three claimants; the hedge-record printed in full. E-0212-CROSS.","VIII.4.1"],
["The Founding of the Freeport","Event","388 AS","A drowned-world queen, a gummi shipwright, a nameless navigator, and one really useful engine. E-0388-PORT.","VIII.4.4"],
["The Night of Broken Veils","Event","902 AS","A filmed feeding, the Omnic Crisis, a spacequake echo over Tokyo: the decade Terra almost woke. E-0902-VEILS.","VIII.5.3"],
["The Energon Panic","Event","934 AS","Cybertron's war reaches the substance markets; the Standard's first crash. E-0934-ENERGON.","VIII.7.4"],
["The War of the Broken Bracket","War","1,112 AS","Soul Edge, wearing Siegfried, takes a grand final; four fronts in a season; two Offices take the field. E-1112-BRACKET.","VIII.11.10"],
["The Spice Concession Crisis","War","771 AS","Three trade wars in a generation over deep-sight; ended at Arrakeen. E-0771-SPICE.","VIII.7.1"],
["The Theomachies","War","c. −9,400 AS","The young Courts' overlapping wars — thrown mountains, churned oceans, a bound wolf — ended by a shared wall. E-THEO.","VIII.2.1"],
["The First Convocation","Event","c. −9,200 AS","Every mountain's summit at once; Odin pre-read the agenda; Thor and Indra had to be separated, then refused to be. E-CONV.","VIII.2.19"],
["The Rabiah Cascade","Event","c. 356 AS","One plane refracted a thousandfold by its own telling; the mirror doctrine's extreme case. E-0356-CASCADE ⟦↑12⟧.","II.E.3"],
["The Caine Adjudication","Case","1,180 AS","The Office of Endings rules on vampire souls; every Kindred court keeps a copy; none agree what it means. E-1180-CAINE.","VIII.15.2"],
["The Isaac Petition","Case","denied","The Custodes formally asked the Throne to close the Basement Loop. Denied. The denial is read more than any treaty.","VIII.15.3"],
["The Harvest Refusal","War","cycle broken","The first refused Reaper harvest in the cycle's recorded history; the soldier's name was Shepard; three endings filed, one certainty.","VIII.9.26"],
["The Delivery","Event","1,204 AS","The Athenaeum Ultima falls to the Pale-as-paperwork; the Collection is cast through the last Aperture. E-1204-DELIVERY ⟦↑ pending⟧.","XI.3"],
["The Registry Communion","Institution","standing","Every library worth its salt, scribe to apex, one grammar. Its apex is orphaned; it does not yet know.","I.9"],
["The Veiled Survey","Institution","standing","The watchers of the unaware worlds. 'They are not ready. We are not waiting — we are writing.'","I.9"],
["The Roadwright Guilds","Institution","standing","Transit itself: rivalrous houses, one function, open lanes, paid tolls.","VIII.4.2"],
["The Circuit","Institution","standing","Sanctioned contest from street bracket to erasure court: pressure valve, measuring instrument, second economy.","VIII.11"],
["The Ledger Standard","Institution","standing","Assay-backed exchange; gil, caps, credits, zenny, and bolts all convert, to Moth's documented horror.","VIII.13.1"],
["The Office of Endings","Institution","standing","Death's federated administrators: punctual, impartial, and offended by comparison to Hell.","W.2"],
["The Storm Office","Institution","standing","Zeus, Thor, Raijin, and colleagues: regional seatholders of one very loud portfolio.","W.2"],
["The Wardens","Order","standing","Slayer to Grey Knight to Liquidator: never one banner, always one war.","VIII.8.26"],
["The Speedwagon Foundation","Institution","standing","The Joestar line's research-philanthropy arm; funds half the Concordance's honest anomaly science and asks embarrassingly good questions.","II.A.2"],
["The Sharlayan Studium","Institution","standing","Eorzea's peer archive — the only local registry the Custodes address as 'colleagues' without qualification.","II.L.5.5"],
["The Orzhov Syndicate","Institution","standing","Ravnica's church-bank: the network's second bank and first futures desk; had exchange rates ready before contact concluded.","II.E.1"],
["The Custodes of the Final Shelf","Order","fallen 1,204 AS","The librarians of the Delivered Collection: they kept writing to the last steady sentence.","0.2"],
["The Athenaeum Absolute","Institution","eternal","The Library of the Omniverse: omniscient clerks, receiving, never descending. Listed because omitting it would be underscoped.","Part Four"],
["The Imperium of Man","Polity","embargoed","The largest civilization on the rolls, self-sealed by policy; its citizens will not know, by decree.","II.G.1.1"],
["The United Federation of Planets","Polity","A5 signatory","The Concordance's conscience; co-author of non-interference; chronically disappointed, institutionally undeterred.","II.F.2.2"],
["The World Government","Polity","A2/A3","An erased century as records policy; the Communion regards it as a standing insult; the erasure is not holding.","II.A.3.2"],
["The Last City","Polity","standing","The Warden-state beneath the Traveler; exports people who fight the Silence and come back.","II.F.5.1"],
["The Kindred Camarilla","Polity","standing","A nation with no land and every city; the Masquerade's senior signatory, arguing with itself since the Adjudication.","II.H.5"],
["Shinra Electric Power Company","Corporate throne","standing","Sovereignty by reactor: the company that owned a planet's soul, classified as a state with better lawyers.","VIII.12.13"],
["Ultratech","Corporate throne","standing","Augmentation cartel and tournament owner; its rites are Circuit-sanctioned and Communion-watched.","II.A.7"],
["Vault-Tec","Corporate throne","legacy","Door-tech contractor; the Architect-firmware allegation is filed with exhibits.","II.J.1.2"],
["CHOAM and the Spacing Guild","Cartel","standing","The spice monopoly's political wing; older than most member states, patient as geology.","II.F.6"],
["The Imagined Order","Faction","standing","The Zero Point's jailers, or curators, depending on the deposition; recruits abductees; files nothing.","II.P.1"],
["The Seven","Faction","standing","The Zero Point's would-be liberators; also recruit abductees; also file nothing; the Communion is equally offended.","II.P.1"],
["The Cybertronian Diaspora","Polity","standing","A nation in convoy: two factions, one dead world, energon lanes as territory.","II.B.4"],
["Hell's Provinces","Polity","standing","Treaty counterparties, never in good faith; the Pit's word is priced accordingly.","W.3"],
["The Keyblade Orders","Order","standing","Small, scattered, disproportionate; their charter predates the locks.","II.O.1.2"],
["The Spice Meridian","Trade route","standing","Deep-sight condensate from one desert to every navigator; chokepoint: Arrakis.","VIII.7.1"],
["The Energon Run","Trade route","standing","The diaspora's lifeline: bonded convoys on posted lanes, collateralized to the frame.","VIII.7.4"],
["The Senzu Corridor","Trade route","standing","Smallest tonnage, highest strategic weight in the omniverse.","VIII.7.11"],
["The Gil–Credit Axis","Trade route","standing","The great retail current; the Freeport takes its cut in the middle and calls it harbor fees.","VIII.13"],
["The Gray Web","Trade route","illicit","Survey-breach smuggling, Embargo-running, soul-futures, counterfeit countersigns; prosecuted with unsettling enthusiasm.","VIII.13.5"],
["Gil","Currency","convertible","The Crystal worlds' coin; the Axis's eastern anchor.","VIII.13.9"],
["Bottlecaps","Currency","convertible","The 2077 branch's faith-backed money; the Ledger recognized it in a ruling economists still teach.","VIII.13.9"],
["Galactic Credits","Currency","convertible","The starfaring polities' common tender, in eleven mutually resentful denominations.","VIII.13.9"],
["Zenny","Currency","convertible","The Gyre worlds' coin; senzu futures settle in it.","VIII.13.9"],
["The Freeport Gazette","Media","daily","The Concordance's paper of record: shipping, brackets, obituaries across eleven rungs; motto: 'Filed before famous.'","W.9"],
["Galaxy News Radio","Media","broadcasting","Three Dog's voice of the wasteland — the 2077 branch's conscience, now syndicated across the sibling futures. 'Fighting the good fight.'","II.J.1"],
["The Daily Bugle, Multiversal Desk","Media","daily","Editor J. Jonah Jameson remains professionally furious on a minimum of fifty-two earths simultaneously.","II.D.1.4"],
["The Bracket Report","Media","per season","The Circuit's broadcast of record: standings, upsets, and the assay-desk segment clerks pretend not to watch.","VIII.11.6"],
["La Revacholière","Media","irregular","Elysium's stubborn local press, printing at the edge of the Pale; every issue that arrives is archived as an act of defiance.","II.N.4"],
["Kamurocho Nightly","Media","tabloid","The district-myth's scandal sheet; wrong daily, essential always.","II.H.3"],
["Lanternwave","Media","continuous","The Betweens' shipping broadcast: weather in the shallows, curl advisories, and the nine-bell silence for ships that do not report.","W.1"],
["The Quiet Bulletin","Media","classified","The Survey's internal digest of the watched worlds: the best journalism in existence, read by forty people, cited by none.","I.9"],
["The 2112 Tapes","Media","received","Transmissions from the Sung Worlds, catalogued as they arrive; true, but only when performed.","II.C.2"],
["Jimmy Firecracker","Celebrity","commentating","Fight commentator; called the Cell Games from inside the blast radius and has anchored the Circuit desk ever since.","VIII.11.6"],
["Three Dog","Celebrity","broadcasting","Voice of the wasteland; last attested at GNR plaza, fighting the good fight.","II.J.1"],
["Saxton Hale","Celebrity","at large","Interdimensional entrepreneur, menace, and Gravel Armistice violation in progress; banned from the Freeport, attends anyway.","II.I.4"],
["Seriah of Vel","Celebrity","historical","Founder-Harbormistress of the Freeport; her statue faces the memorial, not the harbor, on her instruction.","VIII.4.4"],
["Wendy of the Wastes","Celebrity","rising","The blue siren of the Chroma branch; her recordings travel the Story Trade under license, and the wisps travel with them.","II.A.10"],
["Kazuma Kiryu","Celebrity","reluctant","The Dragon of Kamurocho: legend by acclamation, retiree by aspiration, neither by consent.","VIII.12.10"],
["Lector Moth","Celebrity","posthumous?","The measurement doctrine's author, a celebrity among clerks omniverse-wide, to what would have been his horror.","X.2"],
["Sister Quill","Celebrity","posthumous?","Field archivist; her memoir 'I Went There' outsells every treaty commentary combined; the Communion has stopped fighting it.","0.2"],
["The Freeport of Fallen Skies","Place","standing","The refugee-harbor of the middle Betweens: markets, embassies, the Circuit hall, the memorial. Everyone there already knows.","W.9"],
["Embassy Row","Place","standing","Where the players keep their doors; the seating-order wars are in their ninth century.","VIII.4.6"],
["The Bonded Vaults","Place","standing","Neutral custody: drawers unlisted, contents unjudged, the Charter absolute.","VI.2"],
["The Memorial of Drowned Worlds","Place","standing","The first structure the Freeport raised. One plinth is kept empty, in reserve, on purpose.","VIII.4.8"],
["The Last Round","Place","standing","The Freeport's founding bar, second structure ever raised; the table where a Saiyan and a mind-mage drinking is a Tuesday.","W.9"],
["The Tenth District Exchange","Place","standing","Ravnica's trading floor for the network; the Orzhov own the clocks, which tells you everything.","II.E.1"],
["The Ravnica Question","Case","settled 604 AS","Two planes, one name, both real: the pleading that produced the Compact of Mirrors.","VIII.15.1"],
["The Personhood Docket","Case","open","Omnics, warforged, toys, engines, Nobodies, Pals: the slow, real expansion of who counts.","VIII.15.5"],
["The Survey-Breach Docket","Case","crowded","Half the modern criminal docket: the watched worlds are the most tempting market in existence.","VIII.15"],
["The Soul-Property Abolition","Movement","ongoing","The campaign to unmake soul-collateral law entirely; opposed by every Province of Hell, which the movement cites as its best argument.","VIII.6.11"],
["The First Argument","Case","non-justiciable","Who authored everything. Ruled unarguable by the Concordat after the Theomachies; still argued everywhere, nightly, by everyone.","X.5"]
];
