#!/usr/bin/env python3
"""MODULE_INDEX — the map of the 87 modules, generated from their own first lines.

A successor's first question is "what does each of these do", and the honest answer already
exists: every module's docstring opens with its own one-line claim. This collects them into
`handoff/MODULE_INDEX.md`, grouped by the stage of the machine they serve, so onboarding is a
read of one page instead of eighty-seven headers. Generated, never hand-edited -- a hand-kept
copy of information the code already carries is a second writer with no merge strategy.

    python src/module_index.py            # regenerate the page
"""
import ast
import glob
import os
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import silence                                                          # noqa: E402

OUT = os.path.join(HERE, "handoff", "MODULE_INDEX.md")

GROUPS = [
    ("The corpus", ["catalogue_web", "catalogue_aurora", "catalogue_codex", "wiki_source",
                    "feats", "sweep", "read", "completeness", "hostcheck", "hosts", "scout",
                    "endpoint", "ingest_doc", "wikipedia_source"]),
    ("The instrument", ["assay", "magnitude", "anchors", "scope", "reference", "rigor",
                        "identity", "chain", "weave_index"]),
    ("The phases and prose", ["pipeline", "generate", "manifest_builder", "compress_store",
                              "address", "catalog", "retry_synthesis", "tells", "style_audit",
                              "pick_model"]),
    ("The supervision stack", ["overnight", "autostart", "foreman", "standards", "overwatch",
                               "allsweep", "verify_math", "health", "silence", "estate",
                               "dashboard", "coverage", "tuning", "lognames"]),
    ("Transport", ["cascade_bridge"]),
    ("Publishing", ["publish", "build_terminal"]),
]


def first_line(path):
    try:
        tree = ast.parse(open(path, encoding="utf-8").read())
        doc = ast.get_docstring(tree) or ""
        line = doc.strip().splitlines()[0].strip() if doc.strip() else ""
        return line.rstrip(".") or "(no docstring)"
    except Exception:
        silence.note("module_index.py:parse")
        return "(unparseable)"


def main():
    mods = {os.path.basename(p)[:-3]: p
            for p in sorted(glob.glob(os.path.join(HERE, "src", "*.py")))}
    lines = ["# The modules, in one page", "",
             "*Generated by `src/module_index.py` from each module's own first docstring "
             "line. Regenerate after adding a module; never hand-edit.*", ""]
    placed = set()
    for title, names in GROUPS:
        rows = [(n, first_line(mods[n])) for n in names if n in mods]
        if not rows:
            continue
        placed.update(n for n, _ in rows)
        lines.append("## " + title)
        lines.append("")
        for n, fl in rows:
            lines.append(f"- **{n}** — {fl}")
        lines.append("")
    rest = sorted(set(mods) - placed)
    if rest:
        lines.append("## Everything else")
        lines.append("")
        for n in rest:
            lines.append(f"- **{n}** — {first_line(mods[n])}")
        lines.append("")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"{len(mods)} modules -> {os.path.relpath(OUT, HERE)} "
          f"({len(rest)} outside the named groups)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
