#!/usr/bin/env python3
"""MODULE_INDEX — the map of every module in src/, generated from their own first lines.

A successor's first question is "what does each of these do", and the honest answer already
exists: every module's docstring opens with its own one-line claim. This collects them into
`handoff/MODULE_INDEX.md`, grouped by the stage of the machine they serve, so onboarding is a
read of one page instead of a walk through every header in `src/`. Generated, never hand-edited
-- a hand-kept copy of information the code already carries is a second writer with no merge
strategy.

NO COUNT IS WRITTEN DOWN HERE, deliberately. These two paragraphs used to say "the 87 modules"
and "eighty-seven headers"; by the time anyone noticed, the docstring of the module whose entire
argument is that hand-kept copies drift had drifted by twenty-six from whatever `src/` held that
day. The count the page reports is computed live from `glob.glob` at every run, so the only
honest thing to put in prose is that there is one -- never the number itself, which would just
be this paragraph's mistake again with a fresher label.

    python src/module_index.py            # regenerate the page
"""
import argparse
import ast
import os
import sys
import threading

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import silence                                                          # noqa: E402

OUT = os.path.join(HERE, "handoff", "MODULE_INDEX.md")

GROUPS = [
    ("The corpus", ["catalogue_web", "catalogue_aurora", "catalogue_codex", "wiki_source",
                    "feats", "sweep", "read", "completeness", "hostcheck", "hosts", "scout",
                    "endpoint", "ingest_doc"]),
    ("The instrument", ["assay", "magnitude", "anchors", "scope", "reference", "rigor",
                        "identity", "chain", "weave_index"]),
    ("The phases and prose", ["pipeline", "generate", "manifest_builder", "compress_store",
                              "address", "catalog", "retry_synthesis", "tells", "style_audit",
                              "pick_model"]),
    ("The supervision stack", ["overnight", "autostart", "foreman", "standards", "overwatch",
                               "allsweep", "verify_math", "health", "silence", "estate",
                               "dashboard", "coverage", "tuning", "lognames"]),
    ("Transport", ["cascade_bridge"]),
    ("Publishing", ["publish", "build_terminal"]),
]


def first_line(path):
    try:
        tree = ast.parse(open(path, encoding="utf-8").read())
        doc = ast.get_docstring(tree) or ""
        line = doc.strip().splitlines()[0].strip() if doc.strip() else ""
        return line.rstrip(".") or "(no docstring)"
    except Exception:
        silence.note("module_index.py:parse")
        return "(unparseable)"


def _modules():
    """Every module under src/, SUBDIRECTORIES INCLUDED. -> {name: path}.

    `glob(SRC + "/*.py")` does not descend, so `src/deprecated/catalogue_local.py` was never
    listed here even though this page's whole stated purpose is "the map of every module in
    src/" -- the same non-recursive-glob defect allsweep.modules() and sweep_plan.modules()
    were already fixed for (order f42c55355431). Walks and keys the same way allsweep.modules()
    does: a src-relative path with the `.py` dropped, `os.sep` normalised to `/`, so a
    subdirectory module can still be named in GROUPS if it earns a home there.
    `__pycache__` is skipped because it holds no source. (order c453e9dad827)
    """
    src = os.path.join(HERE, "src")
    out = {}
    for root, dirs, files in os.walk(src):
        dirs[:] = [d for d in dirs if d != "__pycache__"]
        for f in files:
            if f.endswith(".py"):
                rel = os.path.relpath(os.path.join(root, f), src).replace(os.sep, "/")
                out[rel[:-3]] = os.path.join(root, f)
    return out


def main():
    ap = argparse.ArgumentParser(
        description="Regenerate handoff/MODULE_INDEX.md from every module's own first "
                     "docstring line. --help does no work: it only builds and prints this "
                     "parser (allsweep.check_import's IMPORT-tier contract).")
    ap.parse_args()
    mods = _modules()
    lines = ["# The modules, in one page", "",
             "*Generated by `src/module_index.py` from each module's own first docstring "
             "line. Regenerate after adding a module; never hand-edit.*", ""]
    placed = set()
    # THE VERDICT IS ACCUMULATED AND CARRIED OUT IN THE EXIT CODE (order e4ccce54d7dd). This
    # detected its own drift, printed it, noted it to state/failures.json -- and then `main()`
    # returned 0, so nothing anywhere went red. This module's whole docstring is an argument
    # that a hand-kept copy of information the code already carries is a second writer with no
    # merge strategy, and it records its OWN docstring having drifted by twenty-six. The one
    # hand-kept list left in the file could detect its own drift and could not make anything
    # fail. The denied-write branch below already accepts that a verdict belongs in the exit
    # code; this verdict simply did not get one.
    #
    # THE PAGE IS STILL WRITTEN. This is an accumulator, not an early return: a stale group name
    # must not also cost the regeneration, and the two failures stay verbally distinct in the
    # printout because their remedies differ -- fix the list, versus re-run when the readers are
    # quiet.
    stale_names = []
    for title, names in GROUPS:
        stale = [n for n in names if n not in mods]
        if stale:
            stale_names.extend(stale)
            print(f"module_index: GROUPS[{title!r}] names a module not in src/: "
                  f"{', '.join(stale)} -- fix the hand-kept list", file=sys.stderr)
            silence.note("module_index.py:stale-group-name")
        rows = [(n, first_line(mods[n])) for n in names if n in mods]
        if not rows:
            continue
        placed.update(n for n, _ in rows)
        lines.append("## " + title)
        lines.append("")
        for n, fl in rows:
            lines.append(f"- **{n}** — {fl}")
        lines.append("")
    rest = sorted(set(mods) - placed)
    if rest:
        lines.append("## Everything else")
        lines.append("")
        for n in rest:
            lines.append(f"- **{n}** — {first_line(mods[n])}")
        lines.append("")
    # tmp + `replace_retry`, not a bare open("w"). A bare open is not a write but a
    # TRUNCATE-THEN-FILL: the target is emptied first and only then refilled, so a crash or a
    # kill in the gap leaves the map permanently truncated, and this page is the one document a
    # successor is told to read first. That is the m6 shape -- this project's oldest species of
    # bug, named in `silence.write_json`'s own docstring, where a single sweep found twelve such
    # sites across ten modules. The tmp name carries pid and thread for the same reason
    # `write_json` does: two writers otherwise collide on the temp file itself and the loser can
    # land a half-built page over the winner's.
    tmp = "%s.%d.%d.tmp" % (OUT, os.getpid(), threading.get_ident())
    with open(tmp, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    # And the verdict is CHECKED. `replace_retry` returns False rather than raising when the
    # rename is denied for all its attempts -- on Windows an open handle IS a denied rename --
    # and a generator that reports "N modules -> handoff/MODULE_INDEX.md" and exits 0 while
    # the file on disk is still last month's map is worse than one that fails loudly.
    if not silence.replace_retry(tmp, OUT):
        sys.stderr.write("module_index: built %d module(s) but the write to %s was DENIED (a "
                         "reader is holding it). The page on disk is the PREVIOUS one -- "
                         "re-run when the readers are quiet.%s"
                         % (len(mods), os.path.relpath(OUT, HERE), chr(10)))
        return 1
    print(f"{len(mods)} modules -> {os.path.relpath(OUT, HERE)} "
          f"({len(rest)} outside the named groups)")
    if stale_names:
        # WHOLE list, never a count: the names ARE the remedy. (Hard Rule 0.)
        sys.stderr.write("module_index: the page was written, but GROUPS names %d module(s) "
                         "that are not in src/: %s -- fix the hand-kept list.%s"
                         % (len(stale_names), ", ".join(stale_names), chr(10)))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
